package com.inhalab.holdfast.support;

import org.springframework.jdbc.core.JdbcTemplate;

/**
 * IDENTITY 시퀀스를 현재 데이터에 맞춘다.
 *
 * <h2>왜 필요한가</h2>
 *
 * <p>모든 {@code id}는 {@code GENERATED BY DEFAULT AS IDENTITY}다
 * ({@code V1__init_schema.sql}). <b>{@code BY DEFAULT}라 id를 명시해 INSERT할 수
 * 있고, 그렇게 넣으면 시퀀스는 올라가지 않는다.</b> 시드 스크립트는 전부 id를
 * 명시한다 — 측정과 시연이 {@code session_id=1}, 좌석 id 연속 구간 같은 <b>고정된
 * 값을 전제</b>하기 때문이다.
 *
 * <p>거기에 {@code TRUNCATE ... RESTART IDENTITY}가 시퀀스를 1로 되돌린다. 그래서
 * 시드가 끝난 DB는 <b>데이터에는 id=1이 있는데 시퀀스는 1을 다음 값으로 들고
 * 있는</b> 상태가 된다. 앱이 자동 생성으로 INSERT하면 그 1을 발급해
 * {@code program_pkey}에 걸린다.
 *
 * <p>관리자 등록 화면(#101)이 실제로 그 500을 냈다. 등록 화면이 생기기 전까지는
 * 앱이 이 다섯 테이블에 INSERT할 일이 없어 드러나지 않았다.
 *
 * <h2>왜 이 방향으로 고쳤나</h2>
 *
 * <p>세 가지 방법이 있었다.
 *
 * <ul>
 *   <li><b>시드가 시퀀스를 맞춘다(채택)</b> — id가 그대로라 측정 경로에 아무
 *       영향이 없다</li>
 *   <li>시드가 id를 명시하지 않는다 — {@code k6}의
 *       {@code SESSION_ID}·{@code SEAT_ID_BASE} 기본값 1과 {@code verify.sql}의
 *       {@code -v session_id=1}이 전부 깨진다. 스크립트가 시드가 만든 id를 읽어
 *       와야 하고, 그것은 측정 절차를 바꾸는 일이다</li>
 *   <li>id 공간을 나눈다 — 시퀀스 시작값을 밀어 두는 방법인데,
 *       {@code TRUNCATE ... RESTART IDENTITY}가 시작값으로 되돌리므로 그 시작값이
 *       <b>가장 큰 시드보다 커야 한다.</b> 좌석은 측정 프로파일에서 1000석까지
 *       가므로 경계가 고정되지 않는다</li>
 * </ul>
 *
 * <h2>테이블을 열거하지 않는다</h2>
 *
 * <p>지금 걸리는 것은 {@code program}·{@code seat_layout}·{@code zone}·{@code seat}
 * ·{@code event_session} 다섯이지만 목록으로 두지 않는다. <b>이 문제는 시드가
 * 새 테이블에 id를 명시하는 순간 다시 생기고, 그때 목록에 추가하는 것을 잊는
 * 것이 이 버그의 원인과 정확히 같은 종류다.</b> IDENTITY 컬럼을 가진 테이블을
 * 전부 훑는다.
 */
public final class IdentitySequences {

    /**
     * 현재 스키마의 IDENTITY 컬럼을 전부 훑어 시퀀스를 {@code max(id)}에 맞춘다.
     *
     * <p>빈 테이블은 {@code setval(seq, 1, false)}가 되어 다음 값이 1이다 —
     * 손대지 않은 것과 같다.
     */
    public static final String RESYNC_SQL = """
            DO $$
            DECLARE
                r   record;
                seq text;
                mx  bigint;
            BEGIN
                FOR r IN
                    SELECT c.table_name, c.column_name
                      FROM information_schema.columns c
                      JOIN information_schema.tables t
                        ON t.table_schema = c.table_schema AND t.table_name = c.table_name
                     WHERE c.table_schema = current_schema()
                       AND t.table_type = 'BASE TABLE'
                       AND c.is_identity = 'YES'
                LOOP
                    seq := pg_get_serial_sequence(quote_ident(r.table_name), r.column_name);
                    CONTINUE WHEN seq IS NULL;
                    EXECUTE format('SELECT max(%I) FROM %I', r.column_name, r.table_name) INTO mx;
                    PERFORM setval(seq, COALESCE(mx, 1), mx IS NOT NULL);
                END LOOP;
            END
            $$;
            """;

    private IdentitySequences() {
    }

    /** id를 명시해 INSERT한 뒤에 부른다. 같은 트랜잭션 안이어도 된다. */
    public static void resync(JdbcTemplate jdbc) {
        jdbc.execute(RESYNC_SQL);
    }
}
