-- V1__init_schema.sql — 초기 스키마.
--
-- docs/erd.md 2절의 15개 테이블과 3절의 유니크 제약 U-1~U-13을 그대로 옮긴다.
-- 이 파일이 정본이 아니라 docs/erd.md가 정본이다 — 컬럼·제약이 어긋나면
-- 이 파일을 고친다.
--
-- id 컬럼은 GENERATED BY DEFAULT AS IDENTITY를 쓴다. GENERATED ALWAYS는
-- 명시적 INSERT에 OVERRIDING SYSTEM VALUE를 요구하는데,
-- load-test/sql/seed.sql이 program·seat_layout·zone·seat·event_session에
-- id를 명시적으로 지정해 INSERT하므로 BY DEFAULT여야 그 스크립트가 그대로 돈다.
--
-- CHECK 제약은 걸지 않는다. 상태값의 유효 범위는 erd.md 주석과 애플리케이션이
-- 책임지고, 이 마이그레이션은 erd.md 3절이 명시한 유니크 제약까지만 다룬다.

-- ── 1. program ──────────────────────────────────────────────────────────
CREATE TABLE program (
    id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        varchar(200)  NOT NULL,
    description text,
    created_at  timestamptz   NOT NULL DEFAULT now()
);

-- ── 2. seat_layout ──────────────────────────────────────────────────────
CREATE TABLE seat_layout (
    id         bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name       varchar(200) NOT NULL,
    created_at timestamptz  NOT NULL DEFAULT now()
);

-- ── 3. zone ─────────────────────────────────────────────────────────────
CREATE TABLE zone (
    id             bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    seat_layout_id bigint       NOT NULL,
    name           varchar(100) NOT NULL,
    sort_order     int          NOT NULL DEFAULT 0,
    CONSTRAINT fk_zone_seat_layout FOREIGN KEY (seat_layout_id) REFERENCES seat_layout (id)
);

-- U-3: 배치도 내 구역명 중복 방지
CREATE UNIQUE INDEX ux_zone_layout_name ON zone (seat_layout_id, name);

-- ── 4. seat ─────────────────────────────────────────────────────────────
CREATE TABLE seat (
    id        bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    zone_id   bigint      NOT NULL,
    seat_no   varchar(20) NOT NULL,
    row_index int         NOT NULL,
    col_index int         NOT NULL,
    CONSTRAINT fk_seat_zone FOREIGN KEY (zone_id) REFERENCES zone (id)
);

-- U-4: 구역 내 좌석번호 중복 방지
CREATE UNIQUE INDEX ux_seat_zone_seatno ON seat (zone_id, seat_no);

-- ── 5. event_session (회차) ─────────────────────────────────────────────
CREATE TABLE event_session (
    id               bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    program_id       bigint       NOT NULL,
    seat_layout_id   bigint       NOT NULL,
    starts_at        timestamptz  NOT NULL,
    ends_at          timestamptz  NOT NULL,
    entry_opens_at   timestamptz  NOT NULL,
    entry_closes_at  timestamptz  NOT NULL,
    reserve_opens_at timestamptz  NOT NULL,
    max_per_user     int          NOT NULL,
    status           varchar(30)  NOT NULL,
    CONSTRAINT fk_event_session_program     FOREIGN KEY (program_id) REFERENCES program (id),
    -- event_session이 seat_layout을 참조하는 이유는 erd.md 4절에 있다 —
    -- seat_inventory를 회차 × 좌석 행으로 사전 생성하려면 그 회차에 어떤
    -- 좌석이 속하는지 알아야 하고, 그 출처가 배치도다.
    CONSTRAINT fk_event_session_seat_layout FOREIGN KEY (seat_layout_id) REFERENCES seat_layout (id)
);

-- ── 6. seat_inventory — 좌석 단위 점유의 경합 대상 (CS-1) ─────────────────
CREATE TABLE seat_inventory (
    id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    session_id  bigint      NOT NULL,
    seat_id     bigint      NOT NULL,
    status      varchar(20) NOT NULL,
    hold_id     varchar(36),   -- 현재 홀드 식별자, nullable (erd.md)
    held_until  timestamptz,   -- 홀드 만료 시각, nullable (erd.md)
    -- 낙관적 락 전략의 명시적 조건부 UPDATE에서 쓸 컬럼이다(concurrency-spec 4.3).
    -- JPA @Version으로 매핑하지 않는다 — 그러면 Hibernate가 모든 저장에 자동으로
    -- 버전 검사를 걸어, 락 전략을 교체해도 하나로 고정된 낙관적 락이 항상 함께
    -- 걸리게 된다.
    version     bigint      NOT NULL DEFAULT 0,
    CONSTRAINT fk_seat_inventory_session FOREIGN KEY (session_id) REFERENCES event_session (id),
    CONSTRAINT fk_seat_inventory_seat    FOREIGN KEY (seat_id) REFERENCES seat (id)
);

-- U-1: 재고 행 중복 생성 방지. 점유의 유일성이 아니라 행의 유일성이므로
-- 5개 전략 전부에 항상 건다(erd.md 3절).
CREATE UNIQUE INDEX ux_seat_inventory_session_seat ON seat_inventory (session_id, seat_id);

-- ── 7. seat_hold — 홀드 이력과 유일성의 정본 (state-transitions.md 0절) ───
CREATE TABLE seat_hold (
    id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    session_id  bigint      NOT NULL,
    seat_id     bigint      NOT NULL,
    hold_id     varchar(36) NOT NULL,   -- 홀드 그룹 식별자(여러 좌석 한 번에)
    user_id     bigint      NOT NULL,   -- CS-6 집계용. 사용자 테이블 없음 — erd.md 4절
    held_until  timestamptz NOT NULL,
    status      varchar(20) NOT NULL,   -- HELD/CONFIRMED/RELEASED
    CONSTRAINT fk_seat_hold_session FOREIGN KEY (session_id) REFERENCES event_session (id),
    CONSTRAINT fk_seat_hold_seat    FOREIGN KEY (seat_id) REFERENCES seat (id)
);

-- U-2: 활성 홀드 중복 차단 — 최후 방어선. none 제외 4개 전략.
--
-- **인덱스 이름과 조건이 load-test/sql/u2-create.sql · u2-drop.sql과 정확히
-- 일치해야 한다.** 이름이나 조건이 어긋나면 시드 스크립트가 이 인덱스가 아닌
-- 다른 인덱스를 만들거나 지워서, 부하 테스트가 U-2 없이 도는데도 있는 줄
-- 알고 측정하게 된다.
--
-- 조건이 status = 'HELD'인 이유(CONFIRMED를 넣지 않는 이유)는 erd.md 3.1·4절에
-- 있다 — CONFIRMED까지 넣으면 "판매된 좌석의 재홀드 차단"까지 이 제약이
-- 떠맡게 되는데, 그 책임은 seat_inventory.status의 조건부 UPDATE에 있다.
--
-- none 베이스라인에서는 seed.sh가 이 인덱스를 DROP한다(u2-drop.sql). 이후
-- 다른 전략으로 다시 측정하면 seed.sh가 u2-create.sql로 재생성하므로, 여기서
-- 만든 것과 정확히 같은 정의로 되돌아와야 한다.
CREATE UNIQUE INDEX ux_seat_hold_active
    ON seat_hold (session_id, seat_id)
    WHERE status = 'HELD';

-- ── 8. user_session_quota — CS-6, 좌석 락과 독립적으로 직렬화(REQ-11) ────
CREATE TABLE user_session_quota (
    id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    session_id  bigint NOT NULL,
    user_id     bigint NOT NULL,
    held_count  int    NOT NULL DEFAULT 0,
    CONSTRAINT fk_user_session_quota_session FOREIGN KEY (session_id) REFERENCES event_session (id)
);

-- U-5: 집계 행 중복 생성 방지
CREATE UNIQUE INDEX ux_user_session_quota_session_user ON user_session_quota (session_id, user_id);

-- ── 9. reservation — 홀드 시점에 생성된다(erd.md 4절) ──────────────────
CREATE TABLE reservation (
    id            bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    session_id    bigint      NOT NULL,
    user_id       bigint      NOT NULL,
    hold_id       varchar(36) NOT NULL,   -- seat_hold 그룹 참조
    status        varchar(30) NOT NULL,   -- HELD/PENDING_PAYMENT/CONFIRMED/CANCELLED/EXPIRED
    total_amount  bigint      NOT NULL DEFAULT 0,
    created_at    timestamptz NOT NULL DEFAULT now(),
    confirmed_at  timestamptz,
    cancelled_at  timestamptz,
    CONSTRAINT fk_reservation_session FOREIGN KEY (session_id) REFERENCES event_session (id)
);

-- U-6: 홀드 그룹당 예약 1건
CREATE UNIQUE INDEX ux_reservation_hold ON reservation (hold_id);

-- ── 10. reservation_seat ────────────────────────────────────────────────
CREATE TABLE reservation_seat (
    id                  bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    reservation_id      bigint NOT NULL,
    seat_inventory_id   bigint NOT NULL,
    CONSTRAINT fk_reservation_seat_reservation      FOREIGN KEY (reservation_id) REFERENCES reservation (id),
    CONSTRAINT fk_reservation_seat_seat_inventory   FOREIGN KEY (seat_inventory_id) REFERENCES seat_inventory (id)
);

-- U-7: 한 예약 안의 좌석 중복 방지
CREATE UNIQUE INDEX ux_reservation_seat_reservation_inventory
    ON reservation_seat (reservation_id, seat_inventory_id);

-- ── 11. payment — Mock PG. REQUESTED/APPROVED/DECLINED/TIMEOUT/FAILED ───
-- state-transitions.md 5절이 정본. CANCELLED는 없다 — 결제 취소는
-- reservation.status가 담당하고 payment 행은 종결 후 바뀌지 않는 이력이다.
CREATE TABLE payment (
    id              bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    reservation_id  bigint       NOT NULL,
    pg_tx_id        varchar(100) NOT NULL,   -- PG 거래 ID — 콜백 멱등키
    status          varchar(20)  NOT NULL,
    amount          bigint       NOT NULL DEFAULT 0,
    created_at      timestamptz  NOT NULL DEFAULT now(),
    approved_at     timestamptz,
    CONSTRAINT fk_payment_reservation FOREIGN KEY (reservation_id) REFERENCES reservation (id)
);

-- U-8: 결제 콜백 멱등성. TIMEOUT 뒤 지연 콜백이 도착해도 같은 시도로 연결된다
-- (state-transitions.md 5.1절).
CREATE UNIQUE INDEX ux_payment_pg_tx_id ON payment (pg_tx_id);

-- ── 12. ticket — 예약좌석당 1장(erd.md 4절) ─────────────────────────────
CREATE TABLE ticket (
    id                     bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    reservation_seat_id    bigint       NOT NULL,
    qr_token               varchar(255) NOT NULL,
    status                 varchar(20)  NOT NULL,   -- ISSUED/USED/VOID
    issued_at              timestamptz  NOT NULL,
    used_at                timestamptz,
    CONSTRAINT fk_ticket_reservation_seat FOREIGN KEY (reservation_seat_id) REFERENCES reservation_seat (id)
);

-- U-9: 예약좌석당 티켓 1장
CREATE UNIQUE INDEX ux_ticket_reservation_seat ON ticket (reservation_seat_id);
-- U-10: QR 토큰 유일성
CREATE UNIQUE INDEX ux_ticket_qr_token ON ticket (qr_token);

-- ── 13. ticket_scan — 검표 이력 ──────────────────────────────────────────
CREATE TABLE ticket_scan (
    id             bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ticket_id      bigint       NOT NULL,
    result         varchar(30)  NOT NULL,   -- ADMITTED/REJECTED_DUPLICATE/REJECTED_TIME/REJECTED_INVALID
    reject_reason  varchar(200),
    scanned_at     timestamptz  NOT NULL DEFAULT now(),
    CONSTRAINT fk_ticket_scan_ticket FOREIGN KEY (ticket_id) REFERENCES ticket (id)
);

-- U-11: 티켓 중복 사용 차단. 실패 스캔 이력은 남기되 성공 입장(ADMITTED)만
-- 티켓당 1건으로 제한한다(erd.md 4절) — U-2와 같은 이유의 부분 인덱스다.
CREATE UNIQUE INDEX ux_ticket_scan_admitted
    ON ticket_scan (ticket_id)
    WHERE result = 'ADMITTED';

-- ── 14. outbox — SELECT ... FOR UPDATE SKIP LOCKED로 집는다(concurrency-spec 6절) ──
CREATE TABLE outbox (
    id                 bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    reservation_id     bigint       NOT NULL,
    notification_type  varchar(50)  NOT NULL,
    status             varchar(20)  NOT NULL,   -- PENDING/SENT/FAILED
    retry_count        int          NOT NULL DEFAULT 0,
    payload            text         NOT NULL,
    next_retry_at      timestamptz,
    created_at         timestamptz  NOT NULL DEFAULT now(),
    sent_at            timestamptz,
    CONSTRAINT fk_outbox_reservation FOREIGN KEY (reservation_id) REFERENCES reservation (id)
);

-- U-12: 중복 발송 방지
CREATE UNIQUE INDEX ux_outbox_reservation_notification ON outbox (reservation_id, notification_type);

-- ── 15. idempotency_record — 예약 요청 멱등키(concurrency-spec 6절) ─────
CREATE TABLE idempotency_record (
    id               bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    idempotency_key  varchar(36)  NOT NULL,
    reservation_id   bigint,                  -- 생성된 예약, nullable (erd.md)
    request_hash     varchar(64)  NOT NULL,
    response_status  int,                     -- 처리 중이면 아직 없음(IDEMPOTENCY_KEY_IN_PROGRESS)
    response_body    text,
    created_at       timestamptz  NOT NULL DEFAULT now(),
    CONSTRAINT fk_idempotency_record_reservation FOREIGN KEY (reservation_id) REFERENCES reservation (id)
);

-- U-13: 예약 요청 멱등성
CREATE UNIQUE INDEX ux_idempotency_record_key ON idempotency_record (idempotency_key);
